### PR TITLE
fix: Update instrumentation to support Elasticsearch v8.11.0

### LINKED ISSUE #1951: Dotty: update tests for elastic.clients.elasticsearch from 8.9.3 to 8.11.0
https://www.nuget.org/packages/elastic.clients.elasticsearch/

### PR DESCRIPTION
**Pull request by tippmar-nr**
Thank you for submitting a pull request.  Please review our [contributing guidelines](/CONTRIBUTING.md) and [code of conduct](https://opensource.newrelic.com/code-of-conduct/).

## Description

Updates our Elasticsearch instrumentation to support version 8.11.0. The signature of an instrumented method changed with the v8.10.0 release.

Resolves #1951

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)

### CODE REVIEW

**Review by nrcventura — APPROVED** [review]

File: tests/Agent/IntegrationTests/UnboundedIntegrationTests/Elasticsearch/ElasticsearchTests.cs [hunk 1]
```diff
@@ -69,6 +69,7 @@ protected ElasticsearchTestsBase(TFixture fixture, ITestOutputHelper output, Cli
                     configModifier.ConfigureFasterSpanEventsHarvestCycle(15);
 
                     configModifier.ForceTransactionTraces();
+                    configModifier.SetLogLevel("finest");
```
Comment (nr-ahemsath) [inline tests/Agent/IntegrationTests/UnboundedIntegrationTests/Elasticsearch/ElasticsearchTests.cs:72]: This is probably leftover from my initial debugging and can be removed.
