### PR TITLE
fix: Prevent multiple SessionCache instances from being created. (#2180)

### LINKED ISSUE #2180: StackExchangeRedis2PlusWrapper can create multiple SessionCache instances
**Description**
Recent customer-supplied memory dumps have revealed that the agent is holding 2 instances of `SessionCache` when we only intend for there to be a single instance. This would appear to be a race condition when `StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer` is called multiple times in quick succession, or it may be related to an agent restart. 

In any case, we should consider adding some locking in the `RegisterProfiler()` callback in `ConnectWrapperV2.cs`

**Expected Behavior**
The agent should use a single instance of the `SessionCache` 

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):*
P3
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
S

### PR DESCRIPTION
**Pull request by tippmar-nr**
Thank you for submitting a pull request.  Please review our [contributing guidelines](/CONTRIBUTING.md) and [code of conduct](https://opensource.newrelic.com/code-of-conduct/).

## Description
Prevents an edge case where multiple `SessionCache` instances could get created if `StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer()` is called multiple times. 

Improves resiliency in `SessionCache.Cleanup()` and adds logging.

Fixes #2180 

# Author Checklist
- [x] Unit tests, Integration tests, and Unbounded tests completed
- [x] Performance testing completed with satisfactory results (if required)

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)

### CODE REVIEW

File: src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/StackExchangeRedis2Plus/SessionCache.cs [hunk 1]
```diff
@@ -107,10 +108,11 @@ private void CleanUp()
                         }
                     }
                 }
+
+                Log.Finest($"SessionCache.Cleanup() removed {cleanedSessions}");
```
Comment (chynesNR) [inline src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/StackExchangeRedis2Plus/SessionCache.cs:112]: Can we do an `if (cleanedSessions > 0)` here to cut down on noise? Or are you concerned that we'll miss the thread ending?

Comment (tippmar-nr) [reply src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/StackExchangeRedis2Plus/SessionCache.cs:112]: I was kind of looking for that message to be a heartbeat for the thread, but I can go either way with it.

Comment (chynesNR) [reply src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/StackExchangeRedis2Plus/SessionCache.cs:112]: Once a minute is probably fine.

**Review by chynesNR — APPROVED** [review]
I don't think this will hurt anything, but I also suspect this won't address the issue we're seeing.

**Review by nrcventura — APPROVED** [review]
