### PR TITLE
Use AppDomain.CurrentDomain.BaseDirectory to get path of appsettings*.json

### LINKED ISSUE #116: appsettings.json file not found for .NET Core app hosted in Windows Service or InProcess IIS
**Description**
When using InProcess IIS hosting or Windows Service, the [Agent looks for the appsettings.json using GetCurrentDirectory()](https://github.com/newrelic/newrelic-dotnet-agent/blob/5ca7c8fe9a455e17e0d1f582ce0c97d368f3621c/src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs#L27). For InProcess IIS or a Windows Service, GetCurrentDirectory() returns the path of the IIS app pool process or - in the case of Windows Service - `C:\Windows\system32\`), not the path of the application.
This is a [known issue](https://github.com/dotnet/aspnetcore/issues/4547) in AspNetCore.
 
This Issue is to change the Agent to use a different way to get to the appsettings.json file.
 
One alternative is suggested in the [AspNetCore Issue](https://github.com/dotnet/aspnetcore/issues/4547).
Another alternative may be to use the [`AppContext.BaseDirectory`](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=netcore-3.1) property instead of GetCurrentDirectory().

**Expected Behavior**
The Agent should find and use appsettings.json if it is located in the current working directory of the application. 

**Steps to Reproduce**
- Create a .NET Core application to be hosted in a Windows Service or InProcess IIS.
- Install the Agent.
- In appsettings.json, set configuration for app name:
    ```
    {
        "NewRelic.AppName": "Descriptive Name"
    }
    ```
- Run the application with the Agent engaged.
- Verify via agent log or New Relic UI that the application name is not what was specified in appsettings.json.

**Your Environment**
.NET Core application, hosted in InProcess IIS or Windows Service.

**Additional context**
Workarounds:
1. IIS apps can be set to run out of process via the web.config which allows the agent to find the correct appsettings.json
```<aspNetCore processPath="dotnet" arguments=".\MVCcore.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="OutOfProcess" />```
2. Use app-local newrelic.config file for [supported Agent configuration](https://docs.newrelic.com/docs/agents/net-agent/configuration/net-agent-configuration) instead of appsettings.json.

Internal NR only: [ref1](https://newrelic.atlassian.net/browse/DOTNET-4385) [ref2](https://newrelic.zendesk.com/agent/tickets/375887) [ref3](https://newrelic.zendesk.com/agent/tickets/364789)
 
**Note about development environment**
N/A

### PR DESCRIPTION
**Pull request by nr-ahemsath**
### Description

This fixes #116 by using `AppDomain.CurrentDomain.BaseDirectory` instead of `Directory.GetCurrentDirectory()` to get the path where an application's `appsettings.json` file(s) should be.

### Testing

Manually tested an ASP.NET Core 2.2 application hosted in a Windows service.  Prior to this fix, this app could not read its New Relic application name setting from `appsettings.json` even though it was there.  After the fix, the app is named correctly as expected.  I also tested some other cases (.NET 5.0 console application, ASP.NET Core 2.2 and 3.1 apps hosted in IIS in-process) and app naming via appsettings.json worked as expected.

### Changelog

Will update changelog once I have a PR # for this PR.

### CODE REVIEW

File: src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs [hunk 1]
```diff
@@ -24,24 +25,33 @@ private static IConfiguration Configuration
...
+            try
+            {
+                applicationDirectory = AppDomain.CurrentDomain.BaseDirectory;
+            }
+            catch (AppDomainUnloadedException)
+            {
+                // Fall back to previous behavior
+                applicationDirectory = Directory.GetCurrentDirectory();
+            }
             var environment = env.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
```
Comment (lspangler584) [inline src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs:38]: Code org nit: Can we move `var env` declaration to right before where it is used on line 38?
Similarly, Can we move the block that sets/checks `var environment` to right before it is used on line 48?

**Review by lspangler584 — APPROVED** [review]
