### PR TITLE
fix: defensively handle null source address in MassTransit instrumentation

### LINKED ISSUE #2055: Object reference error occurs when a MassTransit message is received without an envelope.
**Description**

If you are consuming a MassTransit message without MT envelope, GetQueueData method in https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/MassTransitHelpers.cs throws an exception. It is looking for the source address in the message and expects '_' in the address name, but when the message is just raw JSON, it means no MT envelope and no source address.

**Expected Behavior**
It must be checked if there is a source address then split the parts.

**Steps to Reproduce**

1. Register MT
```
services.AddMassTransit(mcfg =>
    {
        mcfg.UsingRabbitMq((context, rcfg) =>
        {
            rcfg.AddHost(context);

            rcfg.ConfigureEndpoints(context);
            rcfg.UseRawJsonSerializer(RawSerializerOptions.AnyMessageType);
        });
    });
```
2. Send a message
3. config your consumer 
```
protected override void ConfigureConsumer(IReceiveEndpointConfigurator endpointConfigurator
        , IConsumerConfigurator<MyConsumer> consumerConfigurator
        , IRegistrationContext context)
    {
        endpointConfigurator.ConfigureConsumeTopology = false;
        endpointConfigurator.UseRawJsonDeserializer();
        endpointConfigurator.DefaultContentType = new ContentType("application/json");
     
    } 
```

**Your Environment**
NewRelic.Agent : 10.19.2
NewRelic.Agent.Api:10.19.2
NewRelic.LogEnrichers.Serilog : 1.2.0
.Net: 7.0
MassTransit: 8.1.0
Serilog:3.1.0
Serilog.Enrichers.GlobalLogContext:3.0.0
Serilog.Extensions.Hosting: 7.0.0
Serilog.Sinks.Async:1.5.0
Serilog.Sinks.Console:5.0.0

```
"Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.AspNetCore": "Warning",
        "Microsoft.AspNetCore.Authentication": "Information",
        "Microsoft.EntityFrameworkCore.Infrastructure": "Warning",
        "Microsoft.EntityFrameworkCore.Database.Command": "Warning",
        "Microsoft.Hosting.Lifetime": "Information",
        "System": "Warning"
      }
    },
    "Using": [
      "NewRelic.LogEnrichers.Serilog"
    ],
    "Enrich": [ "FromLogContext", "WithNewRelicLogsInContext" ],
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "Console",
              "Args": {
                "formatter": "NewRelic.LogEnrichers.Serilog.NewRelicFormatter, NewRelic.LogEnrichers.Serilog"
              }
            }
          ]
        }
      }
    ]
  }
```

**Additional context**

```
MT-Fault-ExceptionType:	System.NullReferenceException
MT-Fault-InputAddress:	rabbitmqs://serverName/queue-name
MT-Fault-Message:	Object reference not set to an instance of an object.
MT-Fault-StackTrace:	at NewRelic.Providers.Wrapper.MassTransit.MassTransitHelpers.GetQueueData(Uri sourceAddress)
at NewRelic.Providers.Wrapper.MassTransit.NewRelicFilter.Send(ConsumeContext context, IPipe`1 next)
at MassTransit.Middleware.TeeFilter`1.<>c__DisplayClass5_0.<<Send>g__SendAsync|1>d.MoveNext() in /_/src/MassTransit/Middleware/TeeFilter.cs:line 40
--- End of stack trace from previous location ---
at MassTransit.Middleware.OutputPipeFilter`2.SendToOutput(IPipe`1 next, TOutput pipeContext) in /_/src/MassTransit/Middleware/OutputPipeFilter.cs:line 76
at MassTransit.Middleware.OutputPipeFilter`2.SendToOutput(IPipe`1 next, TOutput pipeContext) in /_/src/MassTransit/Middleware/OutputPipeFilter.cs:line 108
at MassTransit.Middleware.DeserializeFilter.Send(ReceiveContext context, IPipe`1 next) in /_/src/MassTransit/Middleware/DeserializeFilter.cs:line 40
at MassTransit.Middleware.RescueFilter`2.MassTransit.IFilter<TContext>.Send(TContext context, IPipe`1 next) in /_/src/MassTransit/Middleware/RescueFilter.cs:line 43
```

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):* P1
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

### PR DESCRIPTION
**Pull request by nr-ahemsath**
Fixes #2055 by checking for a null source address before attempting to use it to get the queue name and type.  If the source address is null, the queue name will be "Unknown" and the type will be "Queue".

I added a story to the backlog to revisit the issue of queue naming when time permits: https://github.com/newrelic/newrelic-dotnet-agent/issues/2061

### CODE REVIEW

File: src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/MassTransitHelpers.cs [hunk 1]
```diff
@@ -17,18 +17,25 @@ private static string[] GetQueueData(Uri sourceAddress)
             return items[items.Length - 1].Split('?');
```
Comment (tippmar-nr) [inline src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/MassTransitHelpers.cs:17]: Do we need to check `items.Length > 0` here? Is it possible for `sourceAddress` to not contain any underscore characters?

Comment (nr-ahemsath) [reply src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/MassTransitHelpers.cs:17]: If `sourceAddress` has no underscores, `Split` will return a list with a single element containing the whole input string.  So, `items.Length` should always be at least 1, and in that case, we will be calling `items[0].Split('?')`.  So, this shouldn't cause any exceptions to be thrown.  However, the queue name could end up being bogus in that case.  I'll put in some more checks and return with sensible defaults.

**Review by tippmar-nr — APPROVED** [review]

**Review by chynesNR — APPROVED** [review]

**Review by jaffinito — APPROVED** [review]

**Review by chynesNR — APPROVED** [review]

**Review by ilhancengiz — APPROVED** [review]

**Review by zikriyeurkmezcengiz — APPROVED** [review]

**Review by dekabe — APPROVED** [review]

**Review by keremdokumaci — APPROVED** [review]

**Review by chynesNR — APPROVED** [review]

**Review by nrcventura — APPROVED** [review]

**Review by jaffinito — APPROVED** [review]
