### PR TITLE
fix: Handle null or empty SQS messages and/or message attributes

### LINKED ISSUE #2811: SQSRequestHandler.ProcessResponse exceptions
**Description**
While grepping through logs for [this issue](https://github.com/newrelic/newrelic-dotnet-agent/issues/2809). I noticed that this exception is very prevalent (well 1660 lines in 8,216,840 log lines).

```csharp
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NewRelic.Providers.Wrapper.AwsSdk.SQSRequestHandler.<>c__DisplayClass2_0.<HandleSQSRequest>g__ProcessResponse|1(Task responseTask)
   at NewRelic.Agent.Extensions.Providers.Wrapper.Delegates.<>c__DisplayClass8_1`1.<OnSuccess>g__EndSegmentWithPossibleException|1()
   at NewRelic.Agent.Extensions.Providers.Wrapper.IAgentWrapperExtensions.HandleExceptions(IAgent agent, Action action)
```

**Expected Behavior**
An exception should not be thrown.

**Steps to Reproduce**
Any app that listens to SQS in the background.

**Your Environment**
Windows Server 2022
dotnet8 
On-prem
Hosted via IIS
NewRelicDotNetAgent_10.30.0_x64.msi (deployed using DSC: ADDLOCAL=NETCoreSupport)
newrelic-infra-amd64.1.57.1.msi (deployed using DSC)

I think the related method is

https://github.com/newrelic/newrelic-dotnet-agent/blob/9673ef1f28a419962a0e50b45b5380fbdaa14528/src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs#L125

### PR DESCRIPTION
**Pull request by nr-ahemsath**
Resolves #2811.

The SQS wrapper is updated to check for:

- A null list of messages
- A empty list of messages
- Null message attributes

before attempting to accept tracing headers from the message attributes.

The SQS integration tests are updated to:

- Test configuring `AWSConfigs.InitializeCollections` either true (default) or false (the condition that surfaced this bug)
  - Distributed tracing across SQS queues is not expected to work when this is configured to be false
- Test receiving an empty message
- Verify no wrapper exceptions or application errors

### CODE REVIEW

**Review by nrcventura — APPROVED** [review]

File: src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs [hunk 1]
```diff
@@ -107,8 +107,11 @@ public static AfterWrappedMethodDelegate HandleSQSRequest(InstrumentedMethodCall
                         var ec = executionContext;
                         var response = ec.ResponseContext.Response; // response is a ReceiveMessageResponse
 
-                        // accept distributed trace headers from the first message in the response
-                        SqsHelper.AcceptDistributedTraceHeaders(transaction, response.Messages[0].MessageAttributes);
+                        if (response.Messages != null && response.Messages.Count > 0 && response.Messages[0].MessageAttributes != null)
```
Comment (tippmar-nr) [inline src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs:110]: Could we refactor this block and the one just like it below into a separate method? Or maybe move the logic to inspect `response.Messages` into the `SqsHelper.AcceptDistributedTraceHeaders()` method?

File: tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkExerciser/AwsSdkExerciser.cs [hunk 2]
```diff
@@ -117,20 +118,30 @@ public async Task<IEnumerable<Message>> SQS_ReceiveMessageAsync(int maxMessagesT
...
-                // delete message
-                await _amazonSqsClient.DeleteMessageAsync(new DeleteMessageRequest
-                {
-                    QueueUrl = _sqsQueueUrl,
-                    ReceiptHandle = message.ReceiptHandle
-                });
+            }
+            catch (Exception ex)
+            {
+                Console.WriteLine($"Caught exception processing response messages: {ex.Message}");
```
Comment (tippmar-nr) [inline tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkExerciser/AwsSdkExerciser.cs:144]: Not sure this try/catch is useful. But in any case, it can't write to the console... ;-)

Comment (nr-ahemsath) [reply tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkExerciser/AwsSdkExerciser.cs]: That was left over from previous debugging attempts.  However, when I removed the try/catch, I had to introduce another null check (for `response.Messages`) and return an empty list of messages if it is null, when running the tests in the "don't initialize empty collections" mode.

File: src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs (hunk 1 above)
Comment (nr-ahemsath) [reply src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs]: Good idea, done.

**Review by nrcventura — DISMISSED** [review]

**Review by tippmar-nr — DISMISSED** [review]

**Review by tippmar-nr — APPROVED** [review]

**Review by nrcventura — APPROVED** [review]
