### PR TITLE
SQL parsing: ignore leading SET statements

### LINKED ISSUE #224: Sql Parsing should deprioritize set statements in multistatement SQL
Our sql parsing logic does not properly prioritize set statements appearing before the real SQL statement being executed. We only attempt to handle it today for SELECT statements.

Here's an example statement from a customer that doesn't work as expected.

SET CONTEXT_INFO = @0; SET NOCOUNT ON; EXEC dbo.spSomeProconOurSystem

This code will result in using the set statement to name the segment, when it should be using the exec statement instead.

As part of this work we should update all of our sql statement parsing to better handle having set statements appear before the real statement. The Cross Agent Test suite should be updated as well.

**MISC**
[New Relic Internal Only] - [Zendesk](https://newrelic.zendesk.com/agent/tickets/389313)

### PR DESCRIPTION
**Pull request by nr-ahemsath**
### Description

Resolves #224:
For a compound SQL statement like `SET @foo = 1; EXEC dbo.someStoredProcedure`, the parsed DB operation will be the `EXEC`, not the `SET`.  (This case *was* previously handled for SELECT, but no other operations.) 

### Testing

Additional unit tests were added to `SqlParserTests.cs` to ensure coverage.

### Changelog

Changelog is updated.

### CODE REVIEW

File: tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs [hunk 1]
```diff
@@ -466,11 +466,29 @@ public void SqlParserTest_TestInnerSelect()
...
 
             var parsedDatabaseStatement = SqlParser.GetParsedDatabaseStatement(DatastoreVendor.MSSQL, CommandType.Text, test);
             Assert.IsNotNull(parsedDatabaseStatement);
-            Assert.AreEqual("(subquery)", parsedDatabaseStatement.Model, string.Format($"Expected model (subquery) but was {parsedDatabaseStatement.Model}", "(subquery)", parsedDatabaseStatement.Model));
-            Assert.AreEqual("select", parsedDatabaseStatement.Operation, string.Format($"Expected operation select but was {parsedDatabaseStatement.Operation}", "select", parsedDatabaseStatement.Operation));
+            Assert.AreEqual(expectedModel, parsedDatabaseStatement.Model, $"Expected model {expectedModel} but was {parsedDatabaseStatement.Model}");
+            Assert.AreEqual(expectedOperation, parsedDatabaseStatement.Operation, $"Expected operation {expectedOperation} but was {parsedDatabaseStatement.Operation}");
+        }
+
+        [Test]
```
Comment (vuqtran88) [inline tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs:478]: [Test] here is redundant I think.

File: src/Agent/NewRelic/Agent/Parsing/SqlParser.cs [hunk 2]
```diff
@@ -129,6 +131,16 @@ public static ParsedSqlStatement GetParsedDatabaseStatement(DatastoreVendor data
                 // Remove comments.
                 var statement = CommentPattern.Replace(commandText, string.Empty).TrimStart();
 
+                if (!IsSingleSqlStatement(statement))
+                {
+                    // Remove leading SET commands
+
+                    // Trimming any trailing semicolons is necessary to avoid having the LeadingSetPattern
+                    // match a SQL statement that ONLY contains SET commands, which would leave us with nothing
+                    statement = statement.TrimEnd(';');
```
Comment (vuqtran88) [inline src/Agent/NewRelic/Agent/Parsing/SqlParser.cs:140]: If you could make ';' a constant, it would be great.

File: tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs (hunk 1 above)
Comment (nr-ahemsath) [reply tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs:478]: It isn't.  If you remove that [Test], after rebuilding one or more times, the Test Explorer will show 5 test cases for the `TestFromGeneratedGibberish` test, which is the next method with the [Test] attributed on it.

File: src/Agent/CHANGELOG.md [hunk 3]
```diff
@@ -8,7 +8,10 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ### New Features
 * **New Feature Template** <br/>
 New Feature Description
-Fixes Issue [#XX](https://github.com/newrelic/newrelic-dotnet-agent/issues/XX)
+
+### Fixes
+Fixes Issue [#224](https://github.com/newrelic/newrelic-dotnet-agent/issues/224): leading "SET" commands will be ignored when parsing compound SQL statements.
```
Comment (vuqtran88) [inline src/Agent/CHANGELOG.md:13]: It is a good practice to also reference the PR at the end of the fix message . For example, "Fixes issue #301 where the agent incorrectly parses server-side configuration causing agent to shutdown.(#310)"

File: src/Agent/NewRelic/Agent/Parsing/SqlParser.cs (hunk 2 above)
Comment (nr-ahemsath) [reply src/Agent/NewRelic/Agent/Parsing/SqlParser.cs]: Done.

File: src/Agent/CHANGELOG.md (hunk 3 above)
Comment (nr-ahemsath) [reply src/Agent/CHANGELOG.md]: Good idea, thanks.

**Review by vuqtran88 — APPROVED** [review]
LGTM
