### PR TITLE
Fixes, updates,and adds NoticeError docs - removes 1000 character limit note in docs

### LINKED ISSUE #1048: The documenation for  NoticeError incorrectly describes the message character limits.
The docs indicate that there is a 1000 character limit for the message parameter. This is not correct.
My testing has show the following:

- This 1000 character limit doc was added to the code in v2.0.8 and expanded out into other areas in v8.28.
- The is no 1000 character limit for NoticeError
- NoticeError creates both Error Events and ErrorTraces
- The limit is different for Error Events and Error Traces
  - Error Events: The message is stored as an attribute with a limit of 255 characters per the Attribute spec.  The Errors spec defers to this for the limit.
  - Error Traces: There does not appear to be a limit on message outside of a total payload limit of 1MB.  I was able to send over a 1000 character message with no issues.

The UI displays data from both types in different areas and there is some overlap.  I had Errors Inbox to show one error with a message from an Error Event - limited to 255 chars and a different error shows the Error Trace message at over 1000 characters.   There must be some logic in the background that picks.

I am creating a PR for the docs site to go along with our own changes to address this.

### PR DESCRIPTION
**Pull request by jaffinito**
## Description

The docs indicate that there is a 1000 character limit for the message parameter. This is not correct.
My testing has show the following:

- This 1000 character limit doc was added to the code in v2.0.8 and expanded out into other areas in v8.28.
- The is no 1000 character limit for NoticeError
- NoticeError creates both Error Events and ErrorTraces
- The limit is different for Error Events and Error Traces
  - Error Events: The message is stored as an attribute with a limit of 255 characters per the Attribute spec.  The Errors spec defers to this for the limit.
  - Error Traces: There does not appear to be a limit on message outside of a total payload limit of 1MB.  I was able to send over a 1000 character message with no issues.

The UI displays data from both types in different areas and there is some overlap.  I had Errors Inbox to show one error with a message from an Error Event - limited to 255 chars and a different error shows the Error Trace message at over 1000 characters.   There must be some logic in the background that picks.

I am created a PR for the docs site to go along with our own changes to address this.

I also spread out the documentation blocks to to each NoticeError method so all are not covered.

Closes #1048

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)
- [ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

### CODE REVIEW

**Comment by jaffinito** [comment]
Docs PR: https://github.com/newrelic/docs-website/pull/6997

File: src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs [hunk 1]
```diff
@@ -280,6 +281,22 @@ void work()
             TryInvoke(work, apiName, apiMetric);
         }
 
+        /// <summary>
+        /// Notice an error identified by a simple message and report it to the New Relic service.
+        /// If this method is called within a transaction,
+        /// the exception will be reported with the transaction when it finishes.
```
Comment (JcolemanNR) [inline src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs:287]: There is no C# `Exception` in this case, maybe change the verbiage to error, or clarify what this means? Are you referring to an `Exception` in the UI?

File: src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs [hunk 2]
```diff
@@ -280,6 +281,22 @@ void work()
             TryInvoke(work, apiName, apiMetric);
         }
 
+        /// <summary>
+        /// Notice an error identified by a simple message and report it to the New Relic service.
+        /// If this method is called within a transaction,
+        /// the exception will be reported with the transaction when it finishes.  
+        /// If it is invoked outside of a transaction, a traced error will be created and reported to the New Relic service.
+        /// Only the string/parameter pair for the first call to NoticeError during the course of a transaction is retained.
+        /// Supports web applications only.
```
Comment (JcolemanNR) [inline src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs:290]: Woah, what? Why would this only support Web applications? Does this mean that if this is called within any custom non-web instrumentation that the error is not actually Noticed?

File: src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs [hunk 3]
```diff
@@ -300,7 +317,8 @@ void work()
         /// Supports web applications only.
```
Comment (JcolemanNR) [inline src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs:317]: I notice you didn't add this... This sounds like a bug though vs something to document, why would it only work for web applications?

**Review by JcolemanNR — APPROVED** [review]
I'm a little worried/confused by the comments about the NoticeError API only supporting web applications, but if this is how it works then this is how it works, and it would be good to document what is in the field.

File: src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs (hunk 3 above)
Comment (jaffinito) [reply src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs:317]: NoticeError should work in any type of application.

File: src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs (hunk 2 above)
Comment (jaffinito) [reply src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs:290]: I don't think the API call has any detection capability, the message seems odd.
