### PR TITLE
fix: Path to agentinfo.json was built incorrectly, leading to file not found errors when running on Linux. (#2156)

### LINKED ISSUE #2156: Agent does not report install type correctly when running on Linux
**Description**
At startup, the agent tries to read from the `agentinfo.json` file in the New Relic "home" folder. If the file does not exist or can't be read, the agent reports `["Install Type", "Unknown"]` in the connect request. 

When running on Linux, the connect request always reports "Unknown" even though an `agentinfo.json` file exists in the New Relic "home" folder.

**Expected Behavior**
The correct install type, read from `agentinfo.json` should be reported when running on Linux.

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):* 
P3
*Suggested T-Shirt size (S, M, L, XL, Unknown):* 
S

### PR DESCRIPTION
**Pull request by tippmar-nr**
Update the hard-coded pathing in `GetAgentInfo()` to use `Path.Combine()` instead for Linux compatibility. 

Fixes #2156.

### CODE REVIEW

File: src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs [hunk 1]
```diff
@@ -200,19 +200,21 @@ private static string GetNewRelicLogLevel()
...
             {
                 try
                 {
                     return JsonConvert.DeserializeObject<AgentInfo>(File.ReadAllText(agentInfoPath));
                 }
-                catch
+                catch (Exception e)
                 {
-                    // Fail silently
+                    Log.Debug(e, $"Could not get agent info from {agentInfoPath}.");
```
Comment (tippmar-nr) [inline src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs:213]:
```suggestion
                    Log.Debug(e, $"Could not deserialize agent info from {agentInfoPath}.");
```

**Review by chynesNR — APPROVED** [review]
Good catch!

File: src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs [hunk 2]
```diff
@@ -200,19 +200,21 @@ private static string GetNewRelicLogLevel()
...
                 }
-                catch
+                catch (Exception e)
                 {
-                    // Fail silently
+                    Log.Debug(e, $"Could not deserialize agent info from {agentInfoPath}.");
                 }
             }
 
+            Log.Debug($"Could not get agent info from {agentInfoPath}. File does not exist.");
```
Comment (nr-ahemsath) [inline src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs:217]: Won't we end up logging this if the file does exist but there was a deserialization error?  Should it be in an `else` clause for the `if (File.Exists)...`?

Comment (tippmar-nr) [reply src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs]: Yep, good catch. I've pushed a change.

**Review by nr-ahemsath — APPROVED** [review]
LGTM! 👍
