### PR TITLE
Profiler - Maintain Instrumentation Points in a Map (Dictionary) instead of a Set (List)

### LINKED ISSUE #269: Reduce the performance impact of large amount instrumentation
**Description**
The New Relic Profiler responds to CLR events for module loading and JIT compilation.  It reads `Instrumentation.xml` files which identify the methods that are to be instrumented.  The signatures of these methods are stored in a List (Set).  When a JIT request is made for any function (instrumented or not), the list is consulted to see if the JITting function should have instrumentation instructions injected.

This process is inefficient and causes performance impacts when this list is large.  As a list, every search results in a linear scan of the list.

The problem is confounded by the fact that instrumentation is agent/system wide.  So, it affects all processes on the server.

**Recommendation**
* Instead of using a list can a look-up structure be used (such as Map) that is keyed based on the signature.
* Could a tree structure organized by Assembly -> Class -> Method Signature be used.  This would result in a much quicker exit for any assembly or class that is not instrumented.

**Steps to Reproduce**
* Build a moderately complex application
* Add an instrumentation xml with 12K methods in it.

**Your Environment**
.NET Framework (but suspect it is also in .NET Core)

**Additional context**
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

### PR DESCRIPTION
**Pull request by jifeingo**
### Description
* Modifies the Profiler to use a `map` structure to maintain instrumentation instead of a 'set'.
* Introduces the concept of an instrumentation point signature (a string that is used as a key)
* Modifies matching logic to use this new structure.

Fixes #269 
### Testing
No new testing required.
Integration tests pass

### CODE REVIEW

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h [hunk 1]
```diff
@@ -45,52 +45,82 @@ namespace NewRelic { namespace Profiler { namespace Configuration
         }
 
         InstrumentationConfiguration(InstrumentationPointSetPtr instrumentationPoints) :
-            _instrumentationPoints(instrumentationPoints),
+            _instrumentationPointsMap(new InstrumentationPointMap()),
```
Comment (nrcventura) [inline src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:48]: Instead of dynamically allocating the InstrumentationPointMap here, we should probably use a field initializer without dynamic allocation to define the map.

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h [hunk 2]
```diff
@@ -45,52 +45,82 @@ namespace NewRelic { namespace Profiler { namespace Configuration
...
-            ipToFind->AssemblyName = function->GetAssemblyName();
-            ipToFind->ClassName = function->GetTypeName();
-            ipToFind->MethodName = function->GetFunctionName();
-            ipToFind->Parameters = std::unique_ptr<xstring_t>(new xstring_t(methodSignature->ToString(function->GetTokenResolver())));
+            auto result = InstrumentationPointSetPtr(new InstrumentationPointSet());
+            for (auto instrumentationPointKVP : *_instrumentationPointsMap) {
+                result->insert(instrumentationPointKVP.second);
+            }
+
+            return result;
```
Comment (nrcventura) [inline src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:69]: Maybe we should keep the original `_instrumentationPoints` field in addition to the map, especially if the map is just holding references to items in the `_instrumentationPoints` set? That would avoid the additional dynamic allocation occurring in this method, which I think is never getting deallocated.

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h [hunk 3]
```diff
@@ -45,52 +45,82 @@ namespace NewRelic { namespace Profiler { namespace Configuration
...
             // Temporarily specifically ignore System.Net.Http.HttpClient instrumentation for .Net 5 and greater, and System.Net.Http.SocketsHttpHandler for framework less than .Net 5
             // until version checking from instrumentation xml is supported.
             if (IsHttpClient5OrGreater(function) || IsSocketsHttpHandlerLessThan5(function))
             {
                 return nullptr;
             }
 
-            auto instPoint = TryGetInstrumentationPoint(ipToFind);
+            auto methodSignature = SignatureParser::SignatureParser::ParseMethodSignature(function->GetSignature()->begin(), function->GetSignature()->end());
+            auto params = new xstring_t(methodSignature->ToString(function->GetTokenResolver()));
```
Comment (nrcventura) [inline src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:82]: Is there a better way to clone a string than dynamically allocating a new one?

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h [hunk 4]
```diff
@@ -45,52 +45,82 @@ namespace NewRelic { namespace Profiler { namespace Configuration
...
+
         InstrumentationPointPtr TryGetInstrumentationPoint(const InstrumentationPointPtr ipToFind) const
         {
-            for (auto current : *_instrumentationPoints)
+            auto const key = ipToFind->GetMatchKey();
+
+            return TryGetInstrumentationPoint(key);
+        }
+
+        InstrumentationPointPtr TryGetInstrumentationPoint(const xstring_t key) const
```
Comment (nrcventura) [inline src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:115]: The `key` parameter should probably be a reference.

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h [hunk 5]
```diff
@@ -45,52 +45,82 @@ namespace NewRelic { namespace Profiler { namespace Configuration
...
+            auto instPoint = TryGetInstrumentationPoint(function->GetAssemblyName(), function->GetTypeName(), function->GetFunctionName(), *params);
             return instPoint;
         }
 
     private:
 
+        InstrumentationPointPtr TryGetInstrumentationPoint(const xstring_t assemblyName,
+            const xstring_t className,
+            const xstring_t methodName,
+            const xstring_t parameters) const
```
Comment (nrcventura) [inline src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:93]: These parameters should probably all be references.

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h [hunk 6]
```diff
@@ -172,6 +202,12 @@ namespace NewRelic { namespace Profiler { namespace Configuration
             instrumentationPoint->MethodName = GetAttributeOrEmptyString(matcherNode, _X("methodName"));
             instrumentationPoint->Parameters = TryGetAttribute(matcherNode, _X("parameters"));
 
+            // void as the parameters means parameterless method call (not all overloads)
+            if (instrumentationPoint->Parameters != nullptr && Strings::AreEqualCaseInsensitive(*(instrumentationPoint->Parameters), _X("void")))
+            {
+                instrumentationPoint->Parameters = std::unique_ptr<xstring_t>(new xstring_t());
```
Comment (nrcventura) [inline src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:208]: Is there a better way to handle this case so that we don't have to dynamically allocate a string? Are we missing the concept of something similar to C#'s `string.Empty`?

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationPoint.h [hunk 7]
```diff
@@ -56,6 +57,24 @@ namespace NewRelic { namespace Profiler { namespace Configuration
...
         }
 
+        xstring_t GetMatchKey()
+        {
+            return Parameters == nullptr
+                ? GetMatchKey(AssemblyName, ClassName, MethodName)
+                : GetMatchKey(AssemblyName, ClassName, MethodName, *Parameters);
+        }
+
+        static xstring_t GetMatchKey(xstring_t assemblyName, xstring_t className, xstring_t methodName)
```
Comment (nrcventura) [inline src/Agent/NewRelic/Profiler/Configuration/InstrumentationPoint.h:67]: These parameters should probably all be `const &`.

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationPoint.h [hunk 8]
```diff
@@ -56,6 +57,24 @@ namespace NewRelic { namespace Profiler { namespace Configuration
...
+        {
+            return xstring_t(_X("[")) + assemblyName + _X("]") + className + _X(".") + methodName;
+        }
+
+        static xstring_t GetMatchKey(xstring_t assemblyName, xstring_t className, xstring_t methodName, xstring_t parameters)
```
Comment (nrcventura) [inline src/Agent/NewRelic/Profiler/Configuration/InstrumentationPoint.h:72]: These parameters should probably all be `const &`.

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h (hunk 1 above)
Comment (jifeingo) [reply src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h]: Was able to do this for the map, but reintroduced the set and that could not be done b/c a different constructor can send it in.

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h (hunk 2 above)
Comment (jifeingo) [reply src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h]: done

File: src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h (hunk 6 above)
Comment (jifeingo) [reply src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:204]: I couldn't figure out a better way to do this.  But, I am no C++ master.

Comment (nrcventura) [reply src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:207]: I think that we might be able to use something like the following `std::make_unique<SomeType>(constructor, parameters, here);`

Comment (nrcventura) [reply src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h:207]: I just realized that this might not be necessary at all...My modern C++ skills are not strong either. The Unique_Ptr should automatically handle that deallocation for us. So I don't think that we need to change anything here, or in the other places where we are using `new` with one of the smart pointers.

**Review by nrcventura — COMMENTED** [review]
I think that everything looks good. Let's get the profiler binaries attached and then we can get this merged.

**Review by nrcventura — APPROVED** [review]
